trigger:
- main

pool:
  name: Default
  demands:
  - agent.name -equals test-deneme

variables:
  token: "sqp_a54a6b2c42fdc112bfa5df974f8faba279519853"

steps:
- script: |
    dotnet sonarscanner begin /k:"FitAI-BackendAPI" /d:sonar.host.url="http://localhost:9000" /d:sonar.token="$(token)"
  displayName: 'SonarQube Begin'

- script: |
    dotnet build
  displayName: 'Build'

- script: |
    dotnet publish FitAIApi\FitAIApi.csproj -f net8.0 -c Release --self-contained -r linux-x64
  displayName: 'Publish'

- task: PowerShell@2
  inputs:
     targetType: 'inline'
     script: |
      Get-ChildItem -Path "$(Pipeline.Workspace)\s\FitAIApi\bin\Release\net8.0\linux-x64\publish" -Recurse -Filter *.config | Remove-Item -Force
      Get-ChildItem -Path "$(Pipeline.Workspace)\s\FitAIApi\bin\Release\net8.0\linux-x64\publish" -Recurse -Filter *.json | Where-Object { $_.Name -notlike '*.deps.json' } | Remove-Item -Force

- task: SSH@0
  inputs:
    sshEndpoint: 'mobven-ssh'
    runOptions: 'commands'
    commands: |
        systemctl stop FitAIApi.service
    readyTimeout: '20000'
  displayName: 'Service-Stop'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'mobven-ssh'
    sourceFolder: '$(Pipeline.Workspace)/s/FitAIApi/bin/Release/net8.0/linux-x64/publish/'
    contents: '**'
    targetFolder: '/var/www/FitAI/FitAIApi'
    readyTimeout: '20000'
  displayName: 'CopyFilesOverSSH'

- task: SSH@0
  inputs:
    sshEndpoint: 'mobven-ssh'
    runOptions: 'commands'
    commands: |
      systemctl start FitAIApi.service
    readyTimeout: '20000'
  displayName: 'Service-Start'

- script: |
    dotnet sonarscanner end /d:sonar.token="$(token)"
  displayName: 'SonarQube End'
